substitutions:
  common_deviceSpecific_comment: "ESP32-C3-super-mini v0.1"

esphome:
  platformio_options:
    board_build.mcu: esp32c3
    board_build.variant: esp32c3
    board_build.flash_mode: dio
    # upload_speed: 921600
    board_build.extra_flags:
      - "-DARDUINO_USB_CDC_ON_BOOT=0"

esp32:
  variant: ESP32C3
  board: esp32-c3-devkitm-1 # seeed_xiao_esp32c3 # esp32dev
  framework:
    type: esp-idf
    # version: "5.0.5" #"4.3.7"
    sdkconfig_options:
      CONFIG_BT_BLE_50_FEATURES_SUPPORTED: y
      CONFIG_BT_BLE_42_FEATURES_SUPPORTED: y
      CONFIG_ESP_TASK_WDT: y
      CONFIG_ESP_TASK_WDT_TIMEOUT_S: "10"

status_led:
  pin:
    number: GPIO8
    inverted: True
    ignore_strapping_warning: True

sensor:
  - platform: internal_temperature
    name: Internal Temperature
    id: sensor_internal_temperature