substitutions:
  comment_esp32: "ESP32 v0.5"

# CHANGES
# v0.5 2026-04-23
#   - renamed substitution from common_deviceSpecific_comment to comment_esp32

esp32:
  board: nodemcu-32s
  framework: 
    type: esp-idf

status_led:
  pin:
    number: GPIO2 #GPIO33
    ignore_strapping_warning: True
    #inverted: True

sensor:
  - platform: internal_temperature
    name: Internal Temperature