substitutions:
  comment_esp8266: "ESP8266 v0.3"

# CHANGES
# v0.3 2026-04-23
#   - renamed substitution from common_deviceSpecific_comment to comment_esp8266
# v0.2 2025-04-18
#   - changed [esphome] > [platform: ESP8266] and [board: d1_mini] to [esp8266] > [board: d1_mini]

esp8266:
  board: d1_mini

status_led:
  pin:
    number: GPIO2 #D4 #BUILTIN_LED
    inverted: True
    # ignore_strapping_warning: True