substitutions:
  common_deviceSpecific_comment: "lg_airconditioner v0.2"
  # Unique device ID in HA
  # deviceid: "lglivingroom" # XXX
  # Unique device name in HA (sensor names will be prefixed by this name)
  # devicename: "LG Living Room" # XXX
  # The input temperature sensor in HA.
  temperature_sensor_entity_id: sensor.my_sensor # XXX
  # Set to "true" if the temperature sensor and Home Assistant use Fahrenheit instead of Celsius.
  fahrenheit: "false" # XXX
  # If multiple controllers are connected to a single indoor unit, only one of them should be
  # configured as "master controller". Slave mode is a new and experimental feature for this
  # ESPHome controller and might not work well.
  # If you're connecting a single controller, this should be set to "false".
  is_slave_controller: "false"

# CHANGES
# v0.3 2026-04-23 Pavol
#   - changed external_components from git source to local source (esphome-lg-controller-local)
#   - fixed '/' characters in entity names to Unicode fraction slash (⁄) for ESPHome 2026 compatibility
# v0.2 2025-06-26 Pavol
#   - test fix for https://github.com/JanM321/esphome-lg-controller/issues/114#issuecomment-3008138904 applied to fork in my github
# v0.1 2025-05-29 Pavol
#   - initial version 

# DOCUMENTATION
# https://github.com/JanM321/esphome-lg-controller/tree/main/esphome

external_components:
  - source:
      type: local
      path: esphome-lg-controller-local/esphome/components
    components: [ lg_controller ]

# external_components:
#   - source: components
#     components: [lg_controller]

uart:
  - id: ac_serial
    tx_pin: GPIO25
    rx_pin:
      number: GPIO26 # Keep in sync with rx_pin below.
      allow_other_uses: true
    baud_rate: 104

# time:
#   - platform: homeassistant
#     id: homeassistant_time

sensor:
  - id: temp_sensor
    platform: homeassistant
    internal: true
    entity_id: ${temperature_sensor_entity_id}
  # - platform: uptime
  #   type: timestamp
  #   name: Last Boot

climate:
  - platform: lg_controller
    name: ""
    # id: ${deviceid}
    uart_id: ac_serial
    rx_pin:
      number: GPIO26 # Keep in sync with rx_pin above.
      allow_other_uses: true
    fahrenheit: ${fahrenheit}
    is_slave_controller: ${is_slave_controller}
    temperature_sensor: temp_sensor
    vane1:
      name: Airflow 1 Up⁄Down
      id: vane_position_1
      icon: mdi:arrow-up-down
    vane2:
      name: Airflow 2 Up⁄Down
      id: vane_position_2
      icon: mdi:arrow-up-down
    vane3:
      name: Airflow 3 Up⁄Down
      id: vane_position_3
      icon: mdi:arrow-up-down
    vane4:
      name: Airflow 4 Up⁄Down
      id: vane_position_4
      icon: mdi:arrow-up-down
    overheating:
      name: Over Heating
      id: overheating
      icon: mdi:heating-coil
    fan_speed_slow:
      name: Fan Speed Slow
      id: fan_speed_slow
      icon: mdi:fan-chevron-down
      mode: box
    fan_speed_low:
      name: Fan Speed Low
      id: fan_speed_low
      icon: mdi:fan-speed-1
      mode: box
    fan_speed_medium:
      name: Fan Speed Medium
      id: fan_speed_medium
      icon: mdi:fan-speed-2
      mode: box
    fan_speed_high:
      name: Fan Speed High
      id: fan_speed_high
      icon: mdi:fan-speed-3
      mode: box
    sleep_timer:
      name: "Sleep Timer (minutes)"
      id: sleep_timer
      icon: mdi:timer-outline
      mode: box
    error_code:
      name: Error Code
      id: error_code
      icon: mdi:alert-circle-outline
    pipe_temp_in:
      name: Pipe Temperature In
      id: pipe_temperature_in
      icon: mdi:thermometer
      unit_of_measurement: "°C"
    pipe_temp_mid:
      name: Pipe Temperature Mid
      id: pipe_temperature_mid
      icon: mdi:thermometer
      unit_of_measurement: "°C"
    pipe_temp_out:
      name: Pipe Temperature Out
      id: pipe_temperature_out
      icon: mdi:thermometer
      unit_of_measurement: "°C"
    defrost:
      name: Defrost
      id: defrost
      icon: mdi:snowflake-melt
    preheat:
      name: Preheat
      id: preheat
      icon: mdi:heat-wave
    outdoor:
      name: Outdoor Unit
      id: outdoor
      icon: mdi:fan
    auto_dry_active:
      name: Auto Dry Active
      id: auto_dry_active
      icon: mdi:fan-clock
    purifier:
      name: Air Purifier
      id: air_purifier
      icon: mdi:pine-tree
    internal_thermistor:
      name: Internal Thermistor
      id: internal_thermistor
      icon: mdi:thermometer
    auto_dry:
      name: Auto Dry
      id: auto_dry
      icon: mdi:fan-clock