substitutions:
  device_name: herna-led
  friendly_name: Herna LED
  room: Herna
  project_name: pavolholes.${friendly_name}
  project_version: "0.4"
  device_type: Shelly RGBW2
  pwm_pin: GPIO15
  button_pin: GPIO5
  button_pullup: INPUT_PULLUP
  button_inverted: "True"
  light_nightBrightnessLevel: "0.20"
  light_eveningBrightnessLevel: "0.50"
  light_fadingStep: "0.05"

packages:
  # higher in the list is higher priority (can overwrite values from includes below)
  common: !include pavolholes_common/common.yaml
  # debug: !include pavolholes_common/debug.yaml
  web_server: !include pavolholes_common/web_server.yaml
  shellyRGBW2: !include pavolholes_common/shellyRGBW2.yaml
  gpio_button: !include pavolholes_common/binary_sensor/gpio_button.yaml


# DEBUG: raw GPIO5 level
sensor:
  - platform: template
    id: gpio5_raw
    name: "${friendly_name} GPIO5 Raw"
    update_interval: 1s
    lambda: |-
      return digitalRead(5);
    unit_of_measurement: ""
    accuracy_decimals: 0
    state_class: measurement
