substitutions:
  device_name: jedalen-led
  friendly_name: Jedalen LED
  room: Chodba Dole
  project_name: pavolholes.${friendly_name}
  project_version: "0.4"
  device_type: Shelly RGBW2
  pwm_pin: GPIO15
  motion_pin: GPIO5
  light_nightBrightnessLevel: "0.01"
  light_eveningBrightnessLevel: "0.20"
  light_fadingStep: "0.05"
  # motion_timer: "300s"

packages:
  # higher in the list is higher priority (can overwrite values from includes below)
  common: !include pavolholes_common/common.yaml
  # debug: !include pavolholes_common/debug.yaml
  web_server: !include pavolholes_common/web_server.yaml # if ESP32 Bluetooth is used this needs to be disabled
  shellyRGBW2: !include pavolholes_common/shellyRGBW2.yaml
  # gpio_motion_for_light: !include pavolholes_common/binary_sensor/gpio_motion_for_light.yaml
