substitutions:
  device_name: obyvacka-airquality
  friendly_name: Obyvacka AirQuality
  room: Obyvacka
  project_name: pavolholes.${friendly_name}
  project_version: "0.2"
  device_type: ESP32 WROOM-32 D1mini
  i2c_sda: GPIO21
  i2c_scl: GPIO22
  bme280_temperature_offset: "-4.4"

# CHANGES
# v0.2 2026-05-03
#   - remote_receiver > binary_sensor: added on_state automation with is_on condition to publish Genius IR codes directly to MQTT
#     Changed from on_press to on_state with condition to handle binary sensor state changes
#     Removed Home Assistant as middleman for IR signal translation
#     Volume Up, Volume Down, Mute, Power now send Genius IR codes via zigbee2mqtt/Obyvacka IR Remote/set/ir_code_to_send
# v0.1

esp32:
  board: wemos_d1_mini32

packages:
  # higher in the list is higher priority (can overwrite values from includes below)
  common: !include pavolholes_common/common.yaml
  esp32: !include pavolholes_common/esp32.yaml
  # debug: !include pavolholes_common/debug.yaml
  # web_server: !include pavolholes_common/web_server.yaml # if ESP32 Bluetooth is used this needs to be disabled
  esp32BluetoothProxy: !include pavolholes_common/esp32BluetoothProxy.yaml # including this changes the framework so the first time it have to be loaded to ESP using USB cable, not OTA!
  bme280: !include pavolholes_common/sensor/bme280.yaml
  ikeaVindriktning: !include pavolholes_common/sensor/ikea_vindriktning.yaml
  ld2410: !include pavolholes_common/sensor/ld2410.yaml

# Extend included sensors
# https://esphome.io/guides/configuration-types.html#extend
# sensor:
#   - id: !extend bme280_temperature
#     filters:
#       - offset: -4.50

# https://esphome.io/components/remote_receiver
remote_receiver:
  pin:
    number: GPIO26
    inverted: true
    mode: INPUT_PULLUP
  dump: samsung #all

binary_sensor:
  - platform: remote_receiver
    id: tv_volume_up
    name: Obyvacka TV Remote Volume Up
    samsung:
      data: 0xE0E0E01F
      nbits: 32
    on_state:
      - if:
          condition:
            binary_sensor.is_on: tv_volume_up
          then:
            - mqtt.publish:
                topic: zigbee2mqtt/Obyvacka IR Remote/set/ir_code_to_send
                payload: CEojrREgAmUCICAB4AkFApcGZaAD4A0LACCgAYAJ4AEFQC+ADQEgAkALgAMAZaAHESACZQIgApcGIAKXBiACIAIgAg==

  - platform: remote_receiver
    id: tv_volume_down
    name: Obyvacka TV Remote Volume Down
    samsung:
      data: 0xE0E0D02F
      nbits: 32
    on_state:
      - if:
          condition:
            binary_sensor.is_on: tv_volume_down
          then:
            - mqtt.publish:
                topic: zigbee2mqtt/Obyvacka IR Remote/set/ir_code_to_send
                payload: BVkjphEzAuAPAQGiBuAVA+ADAUArwAHgBwvAD0AHQANAAUAHQAMLMwIzAq+cWSPlCDMC

  - platform: remote_receiver
    id: tv_mute
    name: Obyvacka TV Remote Mute
    samsung:
      data: 0xE0E0F00F
      nbits: 32
    on_state:
      - if:
          condition:
            binary_sensor.is_on: tv_mute
          then:
            - mqtt.publish:
                topic: zigbee2mqtt/Obyvacka IR Remote/set/ir_code_to_send
                payload: BTQj0RE1AuAPAQGcBuAVA8ABQCfAAeADC0ABwA9AB0ADQAFAB8ADCzUCNQLJnDQj/gg1Ag==

  - platform: remote_receiver
    id: tv_power
    name: Obyvacka TV Remote Power
    samsung:
      data: 0xE0E06798
      nbits: 32
    on_state:
      - if:
          condition:
            binary_sensor.is_on: tv_power
          then:
            - mqtt.publish:
                topic: zigbee2mqtt/Obyvacka IR Remote/set/ir_code_to_send
                payload: CD8j2REoAnACKOAAAUALQANAAQGtBuAVAwEoAoApQCdAAeAHB0Ad4AcT4AMPwAsH1Jw6I9IIKAI=

mqtt:
  broker: 192.168.2.20
  username: !secret mqtt_username
  password: !secret mqtt_password

