substitutions:
  device_name: predsien-display
  friendly_name: Predsien Display
  room: Predsien
  project_name: pavolholes.${friendly_name}
  project_version: "0.1"
  device_type: LILYGO T-Display S3 AMOLED Touch v0.1

packages:
  # higher in the list is higher priority (can overwrite values from includes below)
  common: !include pavolholes_common/common.yaml
  # esp32: !include pavolholes_common/esp32.yaml
  # esp32-c3-super-mini: !include pavolholes_common/esp32-c3-super-mini.yaml
  esp32-lilygo-t-display-s3-amoled-touch: !include pavolholes_common/esp32-lilygo-t-display-s3-amoled-touch.yaml
  # debug: !include pavolholes_common/debug.yaml
  web_server: !include pavolholes_common/web_server.yaml # if ESP32 Bluetooth is used this needs to be disabled
  # esp32BluetoothProxy: !include pavolholes_common/esp32BluetoothProxy.yaml # including this changes the framework so the first time it have to be loaded to ESP using USB cable, not OTA!
  # bh1750: !include pavolholes_common/sensor/bh1750.yaml
  # bme280: !include pavolholes_common/sensor/bme280.yaml
  # ld2420: !include pavolholes_common/sensor/ld2420.yaml
  # gpio_motion: !include pavolholes_common/binary_sensor/gpio_motion.yaml

lvgl:
  id: lvgl_main
  pages:
    - id: weather_forecast
      widgets:
        - obj:
            align: CENTER
            width: 228
            height: 250
            pad_all: 10
            layout:
              pad_column: 0
              type: GRID
              grid_rows: [FR(48), FR(13), FR(13), FR(13), FR(13)]
              grid_columns: [FR(10), FR(40), FR(40), FR(10)]
            widgets:
              - label:
                  text: "\U000F14E4"
                  id: lbl_weather_forecast_condition_icon
                  text_font: icons_100
                  text_align: CENTER
                  grid_cell_row_pos: 0
                  grid_cell_column_pos: 0
                  grid_cell_column_span: 2
                  grid_cell_x_align: CENTER
                  grid_cell_y_align: START

              - label:
                  text: "Unknown"
                  id: lbl_weather_forecast_condition_name
                  text_align: CENTER
                  grid_cell_row_pos: 0
                  grid_cell_column_pos: 2
                  grid_cell_column_span: 2
                  grid_cell_x_align: STRETCH
                  grid_cell_y_align: CENTER

              - label:
                  text: "Feels like:"
                  grid_cell_row_pos: 1
                  grid_cell_column_pos: 1

              - label:
                  text: "--.- °C"
                  id: lbl_weather_forecast_tempap
                  text_align: RIGHT
                  grid_cell_row_pos: 1
                  grid_cell_column_pos: 2
                  grid_cell_x_align: STRETCH

              - label:
                  text: "Maximum:"
                  grid_cell_row_pos: 2
                  grid_cell_column_pos: 1

              - label:
                  text: "--.- °C"
                  id: lbl_weather_forecast_temphi
                  text_align: RIGHT
                  grid_cell_row_pos: 2
                  grid_cell_column_pos: 2
                  grid_cell_x_align: STRETCH

              - label:
                  text: "Minimum:"
                  grid_cell_row_pos: 3
                  grid_cell_column_pos: 1

              - label:
                  text: "--.- °C"
                  id: lbl_weather_forecast_templo
                  text_align: RIGHT
                  grid_cell_row_pos: 3
                  grid_cell_column_pos: 2
                  grid_cell_x_align: STRETCH

              - label:
                  text: "Now:"
                  grid_cell_row_pos: 4
                  grid_cell_column_pos: 1

              - label:
                  text: "--.- °C"
                  id: lbl_weather_outdnoor_now
                  text_align: RIGHT
                  grid_cell_row_pos: 4
                  grid_cell_column_pos: 2
                  grid_cell_x_align: STRETCH

text:
  - platform: lvgl
    name: fr_cond_icon
    widget: lbl_weather_forecast_condition_icon
    mode: text
  - platform: lvgl
    name: fr_cond_name
    widget: lbl_weather_forecast_condition_name
    mode: text
  - platform: lvgl
    name: fr_tempap
    widget: lbl_weather_forecast_tempap
    mode: text
  - platform: lvgl
    name: fr_temphi
    widget: lbl_weather_forecast_temphi
    mode: text
  - platform: lvgl
    name: fr_templo
    widget: lbl_weather_forecast_templo
    mode: text
  - platform: lvgl
    name: wd_out_now
    widget: lbl_weather_outdnoor_now
    mode: text

font:
  - file: "fonts/materialdesignicons-webfont.ttf"
    id: icons_100
    size: 100
    bpp: 4
    glyphs: [
      "\U000F0594", # clear-night
      "\U000F0590", # cloudy
      "\U000F0F2F", # exceptional
      "\U000F0591", # fog
      "\U000F0592", # hail
      "\U000F0593", # lightning
      "\U000F067E", # lightning-rainy
      "\U000F0595", # partlycloudy
      "\U000F0596", # pouring
      "\U000F0597", # rainy
      "\U000F0598", # snowy
      "\U000F067F", # snowy-rainy
      "\U000F0599", # sunny
      "\U000F059D", # windy
      "\U000F059E", # windy-variant
      "\U000F14E4", # sunny-off
      ]
