binary_sensor:
  # Home Assistant Time Helpers
  - platform: homeassistant
    id: ha_time_for_lights_evening
    entity_id: binary_sensor.time_for_lights_evening
    internal: true
    on_state:
      - logger.log:
          format: "[${friendly_name} HA Helper] time_for_lights_evening changed to: %s"
          level: INFO
          args: ["x"]

  - platform: homeassistant
    id: ha_time_for_lights_night
    entity_id: binary_sensor.time_for_lights_night
    internal: true
    on_state:
      - logger.log:
          format: "[${friendly_name} HA Helper] time_for_lights_night changed to: %s"
          level: INFO
          args: ["x"]

  # GPIO binary_sensor (input) for motion sensor.
  - platform: gpio
    pin: ${motion_pin}
    id: binary_sensor_motion
    device_class: motion
    name: Motion
    filters:
      - invert:
    on_press:
      then:
        - if:
            condition:
              - binary_sensor.is_on: timer
              - light.is_on: light_pwm
            then:
              - logger.log:
                  format: "[${friendly_name} Motion] Motion detected, but timer is already running and light is ON so do nothing."
                  level: INFO
            else:
              - logger.log:
                  format: "[${friendly_name} Motion] Motion detected and timer is off..."
                  level: INFO
              - if:
                  condition:
                    - binary_sensor.is_on: ha_time_for_lights_night
                  then:
                    - logger.log:
                        format: "[${friendly_name} Motion] Night time helper is ON, setting brightness to ${light_nightBrightnessLevel}."
                        level: INFO
                    - light.turn_on:
                        id: light_pwm
                        brightness: ${light_nightBrightnessLevel}
                  else:
                    - if:
                        condition:
                          - binary_sensor.is_on: ha_time_for_lights_evening
                        then:
                          - logger.log:
                              format: "[${friendly_name} Motion] Evening time helper is ON, setting brightness to ${light_eveningBrightnessLevel}."
                              level: INFO
                          - light.turn_on:
                              id: light_pwm
                              brightness: ${light_eveningBrightnessLevel}
                        else:
                          - logger.log:
                              format: "[${friendly_name} Motion] No time helper is ON, setting brightness to 1.00."
                              level: INFO
                          - light.turn_on:
                              id: light_pwm
                              brightness: 1.00

  # Template binary_sensor for turning off the light after set amount of time.
  - platform: template
    lambda: 'return id(binary_sensor_motion).state;'
    id: timer
    internal: True
    filters:
      - delayed_off: ${motion_timer}
    on_release:
      - logger.log:
          format: "[${friendly_name} Timer] Motion not detected anymore, turn off LED."
          level: INFO
      - light.turn_off:
          id: light_pwm
          transition_length: 15s