substitutions:
  common_deviceSpecific_comment: "Ikea Vindrinktning v0.1"
  vindrinktning_uart_rx: GPIO16

# CHANGES
# v0.1
#   - initial version 

# DOCUMENTATION
# https://esphome.io/components/sensor/pm1006.html
# https://esphome.io/components/uart#uart

uart:
  - id: uart_pm1006
    rx_pin: ${vindrinktning_uart_rx}
    baud_rate: 9600

sensor:
  - platform: pm1006
    uart_id: uart_pm1006
    pm_2_5:
      name: PM2.5 Concentration